import { Inter } from 'next/font/google';
import './globals.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const listItem = ['Home', 'About', 'contact us', 'Login'];

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div>
          <nav className='bg-teal-100 w-full h-14 flex items-center'>
            <div className='flex justify-between items-center w-full px-4'>
              <div className='font-black text-teal-800 text-3xl'>Next.js</div>
              <div className='md:block hidden'>
                <ul className='flex items-center h-100'>
                  {listItem.map((item, index) => (
                    <li className='mx-3 font-bold font-2xl' key={index}>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <button className='md:hidden block'>
                <i className='fas fa-bars text-red-900'></i>
              </button>
            </div>
            <div className='fixed bg-red-900 inset-0 '>
              <div className='flex justify-between items-center w-full px-4'>
                <div className='font-black text-teal-800 text-3xl'>Next.js</div>
                <div className='md:block hidden'>
                  <ul className='flex flex-col font-black items-center h-100'>
                    {listItem.map((item, index) => (
                      <li className='mx-3 font-bold font-2xl' key={index}>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
                <button className='md:hidden block'>
                  <i className='fas fa-bars text-red-900'></i>
                </button>
              </div>
            </div>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
